# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
  ];
  
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelPackages = pkgs.linuxPackages_lqx;
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.resumeDevice = "/dev/disk/by-uuid/63d875d7-4213-4ae6-acb8-0280f5879d24";
  boot.kernelParams = [ "intel_iommu=on" "iommu=pt" "quiet" "resume=UUID=63d875d7-4213-4ae6-acb8-0280f5879d24" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9c058d11-63b8-4a19-8884-28519aaa8b16";
      fsType = "btrfs";
      options = [ "rw" "relatime" "ssd" "space_cache=v2" "subvolid=273""subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9c058d11-63b8-4a19-8884-28519aaa8b16";
      fsType = "btrfs";
      options = [ "rw" "relatime" "ssd" "space_cache=v2" "subvolid=257" "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/9c058d11-63b8-4a19-8884-28519aaa8b16";
      fsType = "btrfs";
      options = [ "rw" "relatime" "ssd" "space_cache=v2" "subvolid=274" "subvol=@nix" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/18B2-C53C";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/63d875d7-4213-4ae6-acb8-0280f5879d24"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
